// Central icon exports used throughout the app
// Using react-icons/bs (Bootstrap Icons) and react-icons/fi (Feather Icons)

export {
  // Status / feedback
  BsCheckCircleFill as IconCheck,
  BsExclamationTriangleFill as IconWarn,
  BsXCircleFill as IconError,
  BsInfoCircleFill as IconInfo,
  BsShieldFill as IconShield,
  BsShieldLockFill as IconShieldLock,
  BsEyeFill as IconEye,
  BsEyeSlashFill as IconEyeOff,

  // Actions
  BsClipboard2Fill as IconCopy,
  BsClipboard2CheckFill as IconCopied,
  BsArrowRepeat as IconRefresh,
  BsDownload as IconDownload,
  BsToggleOn as IconToggleOn,
  BsToggleOff as IconToggleOff,

  // Objects / concepts
  BsLockFill as IconLock,
  BsKeyFill as IconKey,
  BsFingerprint as IconFingerprint,
  BsTerminalFill as IconTerminal,
  BsFileTextFill as IconFile,
  BsLightbulbFill as IconTip,
  BsBookmarkFill as IconBookmark,
  BsPersonFill as IconPerson,
  BsGearFill as IconGear,
  BsWifiOff as IconWifiOff,
  BsWifi as IconWifi,
  BsQuestionCircleFill as IconHelp,
  BsBoxArrowUpRight as IconExternal,
  BsChevronRight as IconChevron,
  BsStars as IconStars,
  BsBan as IconBan,
} from "react-icons/bs";

export {
  FiCopy as FiCopy,
  FiCheck as FiCheck,
  FiRefreshCw as FiRefresh,
  FiDownload as FiDownload,
  FiEye as FiEye,
  FiEyeOff as FiEyeOff,
  FiAlertTriangle as FiWarn,
  FiInfo as FiInfo,
  FiShield as FiShield,
  FiKey as FiKey,
  FiLock as FiLock,
  FiUser as FiUser,
  FiSettings as FiSettings,
  FiCode as FiCode,
  FiTerminal as FiTerminal,
  FiBookmark as FiBookmark,
  FiExternalLink as FiExternal,
  FiAlertCircle as FiAlert,
  FiCheckCircle as FiCheckCircle,
  FiXCircle as FiXCircle,
  FiStar as FiStar,
  FiZap as FiZap,
  FiSlash as FiSlash,
  FiEdit as FiEdit,
  FiWifi as FiWifi,
  FiCpu as FiCpu,
  FiDatabase as FiDatabase,
  FiGlobe as FiGlobe,
  FiCamera as FiCamera,
  FiUserCheck as FiUserCheck,
  FiCheckSquare as FiCheckSquare,
} from "react-icons/fi";
